<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.*" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BSC.Application\BSC.Application.csproj" />
    <ProjectReference Include="..\BSC.Infrastructure\BSC.Infrastructure.csproj" />
  </ItemGroup>

</Project>
